apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}-deployment
spec:
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: {name}
        image: {image-name}:{image-version}
---
apiVersion: v1
kind: Service
metadata:
  name: {name}-service
spec:
  selector:
    app: {name}
  ports:
    - protocol: TCP
      port: {image-port}
      targetPort: {image-port}
